---
title: "p8105_hw6_co2616"
output: github_document
date: "2025-12-01"
---

loading key packages
```{r}
library(tidyverse)
library(p8105.datasets)
```

## Problem 1

loading and cleaning homicide dataset

```{r}
homicide_df = 
  read_csv("data/homicide_data.csv", na = c("NA", ".", "")) %>% 
  janitor::clean_names() %>%
  mutate(
    resolved = as.numeric(disposition == "Closed by arrest"),
    victim_age = as.numeric(victim_age)) %>% 
  unite("city_state", city, state, sep = ", " ) %>% 
  filter(
    !city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"),
    victim_race %in% c("White", "Black") 
        )
```

**Baltimore, MD**

```{r}
homicide_fit =
homicide_df %>% 
  filter(city_state == "Baltimore, MD") %>% 
  glm(resolved ~ victim_sex + victim_age + victim_race, data = .)

homicide_fit %>%  
  broom::tidy() %>% 
  filter(term == "victim_sexMale") %>% 
  mutate(
    OR = exp(estimate),
    conf.low = exp(estimate - 1.96 * std.error),
    conf.high = exp(estimate + 1.96 * std.error)
    ) %>% 
  select(term, log_OR = estimate, OR, conf.low, conf.high) %>%  
  knitr::kable(digits = 3)
  
```

**All Cities**

```{r}
city_glm = 
  homicide_df %>% 
  nest(data = -city_state) %>% 
  mutate(
    log_fit = map(data, \(df) glm(resolved ~ victim_sex + victim_age + victim_race, data = df)),
    results = map(log_fit, broom::tidy)) %>% 
  select(-data, -log_fit) %>%  
  unnest(results)

city_glm_results =
city_glm %>% 
  filter(term == "victim_sexMale") %>% 
  mutate(
   OR = exp(estimate),
   conf.low = exp(estimate - 1.96 * std.error),
   conf.high = exp(estimate + 1.96 * std.error)
    ) %>% 
  select(city_state, term, OR, conf.low, conf.high)
```

plotting results
note: need to fix ordering and add comments
```{r}
city_glm_results %>%
  arrange(OR) %>% 
  ggplot(aes(x = city_state, y = OR)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2, color = "steelblue") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 1))
  
```

## Problem 2

```{r}
data("weather_df")
```

```{r}
boot_sample = function(df) {
  
  sample_frac(df, size = 1, replace = TRUE)
}
```

```{r}
boot_straps = 
  tibble(
    iter = 1:100
  ) %>% 
  mutate(
    bootstrap_sample = map(iter, \(i) boot_sample(df = weather_df))
  )
```

```{r}
bootstrap_results = 
  boot_straps %>% 
  mutate(
    models = map(bootstrap_sample, \(df) lm(tmax ~ tmin + prcp, data = df)),
    glance_results = map(models, broom::glance),
    tidy_results = map(models, broom::tidy)
    ) %>%  
  select(-bootstrap_sample, -models) %>%  
  unnest(glance_results) %>% 
  select(iter, r.squared, tidy_results) %>% 
  unnest(tidy_results) %>% 
  select(iter, r.squared, term, estimate) %>% 
  pivot_wider(
    names_from = term,
    values_from = estimate
  ) %>% 
  mutate(
    beta_ratio = tmin/prcp
  )
```

```{r}
bootstrap_results %>% 
  ggplot(aes(x = beta_ratio)) +
  geom_density()
```
note: add comments

```{r}
bootstrap_results %>% 
  ggplot(aes(x = r.squared)) +
  geom_density()
```
note: add comments

```{r}
bootstrap_results %>% 
  select(iter, r.squared, beta_ratio) %>% 
 summarise(
   r_cis_lower = quantile(r.squared, 0.025),
   r_cis_upper = quantile(r.squared, 0.975),
   beta_cis_lower = quantile(beta_ratio, 0.025),
   beta_cis_upper = quantile(beta_ratio, 0.975),
 ) %>% 
  knitr::kable(digits = 3)
```